import Head from 'next/head'
import Image from 'next/image';

import styles from "../styles/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hoang Jewellers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="hero" className={styles.hero}>
        <div className={styles.csContainer}>
          <div className={styles.csFlexGroup}>
            <span className={styles.csTopper}>Hoang Jewellers</span>
            <h1 className={styles.csTitle}>Explore the World with Exciting People</h1>
            <p className={styles.csText}>
              Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Nibh tortor id aliquet lectus proin nibh
              condimentum.
            </p>
            <a href="" className={styles.csButtonSolid}>Explore More</a>
            <a href="" className={styles.csButtonTransparent}>
              <Image
                className={styles.csImg}
                loading="lazy"
                decoding="async"
                src="/images/placeholder.png"
                alt="play icon"
                width="17"
                height="17" />
                Learn More
            </a>
          </div>
        </div>
        <picture className={styles.csPicture}>
          <Image src="/images/landing.jpg" width="1920" height="850" alt="background" />
        </picture>        
      </section>

      <section id="services" className={styles.services}>
        <div className={styles.card}>
          <picture>
            <Image
              aria-hidden="true"
              decoding="async"
              src="/images/placeholder.png"
              alt="appliance"
              width="48"
              height="48" />
          </picture>
          <h2>Service 1</h2>
          <p>Talk about the service with keywords people will be searching for it by. Keep it 1-2 sentences.</p>
        </div>
        <div className={styles.card}>
          <picture>
            <Image
              aria-hidden="true"
              decoding="async"
              src="/images/placeholder.png"
              alt="appliance"
              width="48"
              height="48" />
          </picture>
          <h2>Service 2</h2>
          <p>Talk about the service with keywords people will be searching for it by. Keep it 1-2 sentences.</p>
        </div>
        <div className={styles.card}>
          <picture>
            <Image
              aria-hidden="true"
              decoding="async"
              src="/images/placeholder.png"
              alt="appliance"
              width="48"
              height="48" />
          </picture>
          <h2>Service 3</h2>
          <p>Talk about the service with keywords people will be searching for it by. Keep it 1-2 sentences.</p>
        </div>
      </section>

      <section id="sbs" className={styles.sbs}>
        <div className={styles.csContainer}>
          <div className={styles.csLeft}>
            <picture className={`${styles.csPicture} ${styles.csPicture1}`}>
              <Image src="/images/placeholder.png" alt="house" width="400" height="400" />
            </picture>
            <picture className={`${styles.csPicture} ${styles.csPicture2}`}>
              <Image src="/images/placeholder.png" alt="house" width="400" height="400" />
            </picture>            
          </div>

          <div className={styles.csRight}>
            <span className={styles.csTopper}>About Us</span>
            <h2 className={styles.csTitle}>About Company Title</h2>
            <p className={styles.csText}>
              In consequat tincidunt turpis sit amet imperdiet. Praesent className officelan nonatoureanor mauris laoreet, iaculis
              libero quis. Curabitur et tempus eri consequat tincidunt turpis sit amet imperdiet. Praesent nonatourean olei
              aptent taciti sociosqu ad litora torquent per.
            </p>
            <p className={styles.csText}>
              In consequat tincidunt turpis sit amet imperdiet. Praesent className officelan nonatoureanor mauris laoreet, iaculis
              libero quis. Curabitur et tempus eri consequat tincidunt turpis sit amet imperdiet. Praesent nonatourean olei
              aptent taciti sociosqu ad litora torquent per.
            </p>
            <div className={styles.csFlexGroup}>
              <p className={styles.csFlexP}>
                In consequat tincidunt turpis sit amet imperdiet. Praesent classNameei consequat tincidunt turpis sit amet
                imperdiet for mind.
              </p>
              <span className={styles.csName}>Justin Time</span>
              <span className={styles.csJob}>CEO-Founder</span>
              <Image
                className={styles.csQuoteIcon}
                loading="lazy"
                decoding="async"
                src="/images/placeholder.png"
                alt="gavel"
                width="136"
                height="77" />
            </div>
            <a href="/about" className={`${styles.buttonSolid} button-solid`}>More About Us</a>
          </div>
        </div>
      </section>

      <section id="sbs-r" className={styles.sbsR}>
        <div className={styles.csContainer}>
          <div className={styles.csLeft}>
            <picture className={`${styles.csPicture} ${styles.csPicture1}`}>
              <Image src="/images/placeholder.png" alt="house" width="400" height="400" />
            </picture>
            <picture className={`${styles.csPicture} ${styles.csPicture2}`}>
              <Image src="/images/placeholder.png" alt="house" width="400" height="400" />
            </picture>
          </div>

          <div className={styles.csRight}>
            <span className={styles.csTopper}>About Us</span>
            <h2 className={styles.csTitle}>About Company Title</h2>
            <p className={styles.csText}>
              In consequat tincidunt turpis sit amet imperdiet. Praesent className officelan nonatoureanor mauris laoreet, iaculis
              libero quis. Curabitur et tempus eri consequat tincidunt turpis sit amet imperdiet. Praesent nonatourean olei
              aptent taciti sociosqu ad litora torquent per.
            </p>
            <p className={styles.csText}>
              In consequat tincidunt turpis sit amet imperdiet. Praesent className officelan nonatoureanor mauris laoreet, iaculis
              libero quis. Curabitur et tempus eri consequat tincidunt turpis sit amet imperdiet. Praesent nonatourean olei
              aptent taciti sociosqu ad litora torquent per.
            </p>
            <div className={styles.csFlexGroup}>
              <p className={styles.csFlexP}>
                In consequat tincidunt turpis sit amet imperdiet. Praesent classNameei consequat tincidunt turpis sit amet
                imperdiet for mind.
              </p>
              <span className={styles.csName}>Justin Time</span>
              <span className={styles.csJob}>CEO-Founder</span>
              <Image
                className={styles.csQuoteIcon}
                loading="lazy"
                decoding="async"
                src="/images/placeholder.png"
                alt="gavel"
                width="136"
                height="77" />
            </div>
            <a href="/about" className={`${styles.buttonSolid} button-solid`}>More About Us</a>
          </div>
        </div>
      </section>

      <section id="cta" className={styles.cta}>
        <div className={styles.container}>
          <h2 className={styles.title}>
            Get It Done <br/>
            With Us Today
          </h2>
          <p>
            Say something catchy, informative, and encouraging to click the button to go to the contact page. I like to add
            these to the bottom of all pages.
          </p>
          <a href="/contact" className={`${styles.buttonSolid} button-solid`}>Get an Estimate Now</a>
        </div>

        <picture>
          <Image src="/images/placeholder.png" className="cs-picture" width="1920" height="1280" alt="background" />
        </picture>        
      </section>
    </>
  )
}
